# Configure the starship prompt

format = """
$username[@](bold)\
$hostname \
$conda\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$directory\
$line_break\
$shell\
$character
"""

[directory]
truncation_length = 10
truncation_symbol = '…/'
truncate_to_repo = false

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[conda]
format = 'env:[$environment]($style) '

[git_status]
disabled = false
