name: default
channels:
  - conda-forge
dependencies:
  - python==3.11
  - nodejs
  - conda-lock
  - pip
  # Dev
  - livereload
  - tqdm
  - black
  - flake8
  - rich
  # Base Scipy
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - cmocean
  - seaborn
  - xarray
  - dask
  - numba
  # Jupyter
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupytext
  - jupyterlab-spellchecker
  - jupyterlab-myst
  - jupyter-resource-usage
  - mamba_gator
  - nb_conda_kernels
  # Geo
  - pyproj
  - pykdtree
  - xlandsat
  # Fatiando
  - pooch
  - verde
  - harmonica
  - boule
  - ensaio
  # GMT
  - gmt>=6.5.0
  - pygmt>=0.11.0
  # Misc
  - tectonic
  - matplotlib-scalebar
